### PR TITLE
Fix profiler session already began error

### PR DESCRIPTION
**Pull request by Tomasz-Kluczkowski**
Fixes an issue with asynchronous call to an API which were causing `SessionProfiler` to report 'session is already began'.

The instantiation of the profiler was moved into the `__call__` method of the `EasyProfileMiddleware`.

### CODE REVIEW

**Comment by Tomasz-Kluczkowski** [comment]
I have tested it locally on my little Flask app by sending asynchronous calls to the API with:
curl <url> & curl <url>

Confirmed working ok.

**Comment by dmvass** [comment]
@Tomasz-Kluczkowski  good job! Can you please update CHANGELOG and add test case with two or more concurrent middleware calls, application handler should sleep 1 sec, please use threading module.

**Comment by dmvass** [comment]
Closes #13

**Comment by Tomasz-Kluczkowski** [comment]
Ok, I have added a concurrency test, which with the old setup fails and works with the new one.

Had a go at concurrency.futures initially, then I remembered this must work for Python 2 :) and went to threading.

Let me know if this looks now ok. For some reason codecove complains about patch coverage but I cannot find any lack of testing there...

**Comment by dmvass** [comment]
LGTM! thanks

**Pull request merged**
